# Generated by Django 5.0.6 on 2024-06-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='xray_scan',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
