# Generated by Django 5.0.6 on 2024-06-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_xray_scan'),
        ('users', '0002_staff'),
    ]

    operations = [
    ]
