# Generated by Django 5.0.6 on 2024-06-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_i'),
    ]

    operations = [
        migrations.DeleteModel(
            name='i',
        ),
    ]
